name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 76.29.169.184 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          rsync -avz --delete $GITHUB_WORKSPACE/ faisl@76.29.169.184:/var/www/html/
